kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: passbolt-rootless

---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: passbolt-rootless-build
  labels:
    app: passbolt-rootless
    edition: MIT
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'passbolt-rootless:latest'
  resources:
    limits:
      cpu: '1'
      memory: 2Gi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'docker.io/passbolt/passbolt:latest-ce-non-root'
      env:
        - name: PB_VERSION
          value: 4.0.0-2-ce-non-root
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: >
      FROM docker.io/passbolt/passbolt:${PB_VERSION}

      USER 0

      ENV SUMMARY="Passbolt API Server for OpenShift" \
          DESCRIPTION="This image creates the Passbolt API image for use at OpenShift"

      LABEL summary="$SUMMARY" \
            maintainer="$maintainer"  \      
            description="$DESCRIPTION" \
            io.k8s.description="$DESCRIPTION" \
            io.k8s.display-name="Passbolt API Server" \
            io.openshift.expose-services="8080:4433" \
            io.openshift.tags="Passbolt API Server" \
            release="${PB_VERSION}"

      RUN curl -JLs
      https://raw.githubusercontent.com/ll911/passbolt-non-root/main/entrypoint.sh
      -o /docker-entrypoint.sh \
        && chmod 775 /docker-entrypoint.sh \
        && chmod -R 775 /etc/passbolt \
        && chmod 666 /etc/environment \
        && chmod 660 /etc/passwd \
        && chmod 660 /etc/supervisor/conf.d/cron.conf

      USER www-data